name: Check for Broken Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0' # every Sunday at 2 AM UTC

jobs:
  lychee-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lychee on the site
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress ./
